spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.116/sell?useUnicode=true&characterEncoding=utf-8&useSSL=true
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /sell
logging:
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'